# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 compile:
   runs-on: Agent1

   steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Node.js
     uses: actions/setup-node@v4
     with:
       node version: '18.19.1'
   - name: Frondtend Compilation  (Syntax check)
     run: |
       cd client
       find . -name "* .js" -exec node  --check {} +

   - name: Backend compilation (Syntax check)
     run: |
       cd client
       find . -name "* .js" -exec node  --check {} +
     
 
  
